
 /**8**/
 ALTER TABLE SANPHAM
ADD CONSTRAINT KIEMTRA_GIA CHECK(GIA > 500)
GO
/**9**/
ALTER TABLE CTHD
ADD CONSTRAINT KIEMTRA_SL CHECK(SL >= 1)
GO
/**10**/
ALTER TABLE KHACHHANG
ADD CONSTRAINT KIEMTRA_NGAY CHECK(NGDK >= NGSINH)
/**11**/
GO
create trigger kiem_tra_HOADON 
on HOADON
FOR INSERT
AS
IF UPDATE(NGHD)
BEGIN
IF(SELECT COUNT(*) FROM KHACHHANG K, INSERTED I
WHERE K.MAKH = I.MAKH AND
I.NGHD < K.NGDK)>0
BEGIN
PRINT ' NGHD PHAI LON HON NGDK'
rollback transaction ;
END
ELSE
BEGIN 
PRINT ' THANH CONG'
END
END
GO
/**12**/
CREATE TRIGGER KIEMTRA_NGAYVL
ON NHANVIEN
FOR UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL
 FROM  INSERTED
 
 IF(@NGVL>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MANV=I.MANV))
  BEGIN
   ROLLBACK TRAN
   PRINT 'LOI'
  END
 ELSE
  PRINT' THANHCONG'
  GO
  /**13**/
  CREATE TRIGGER KIEMTRA_HOADON
ON CTHD
FOR DELETE,UPDATE
AS
 DECLARE @SL  INT,
   @SOHD INT

 SELECT @SL=COUNT(A.SOHD),@SOHD=D.SOHD
 FROM  DELETED D,CTHD A
 WHERE A.SOHD=D.SOHD
 GROUP BY  D.SOHD

 IF(@SL<1)
  BEGIN
   DELETE FROM HOADON
   WHERE  SOHD=@SOHD
   PRINT 'DA DELETE CTHD CUOI CUNG CUA HOADON TREN'
  END
  GO
  /**14**/
  CREATE TRIGGER THEM_HOADON
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=0
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'DA THEM TRI GIA BAN DAU =0' 
 /**15**/
 GO
 CREATE TRIGGER THEM_KHACHHANG
ON KHACHHANG
FOR INSERT
AS
 DECLARE @MAKH CHAR(4)

 SELECT @MAKH=MAKH
 FROM  INSERTED
 
 UPDATE KHACHHANG
 SET  DOANHSO=0
 WHERE MAKH=@MAKH

 PRINT 'DA THEM KHACH TRI GIA=0'