CREATE TABLE KHACHHANG
(
MAKH CHAR (4) PRIMARY KEY,
HOTEN VARCHAR (40) NOT NULL,
DCHI VARCHAR (50) NOT NULL,
SODT VARCHAR (20) NOT NULL,
NGSINH SMALLDATETIME,
NGDK SMALLDATETIME,
DOANHSO money,
);
GO
CREATE TABLE NHANVIEN
(
MANV CHAR(4) PRIMARY KEY,
HOTEN VARCHAR(40),
SODT VARCHAR(20),
NGVL SMALLDATETIME, 
);
CREATE TABLE SANPHAM 
(
MASP CHAR(4) PRIMARY KEY,
TENSP VARCHAR(40),
DVT VARCHAR(20),
NUOCSX VARCHAR(40),
GIA MONEY,
);
GO
CREATE TABLE HOADON
( 
SOHD INT PRIMARY KEY,
NGHD SMALLDATETIME ,
MAKH CHAR(4),
MANV CHAR(4),
TRIGIA MONEY,
);
GO
CREATE TABLE CTHD
(
SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD) ,
MASP CHAR(4) FOREIGN KEY REFERENCES SANPHAM(MASP),
SOLUONG INT,
PRIMARY KEY (SOHD, MASP)
);
GO
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20);
GO
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;
GO
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);
GO
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

